### ISSUE TITLE
AppImage fails to start because abstract-socket is missing

### ISSUE THREAD

**Issue by xyzz** [jeffvli/sonixd#153]
**Describe the bug**
Running the appimage on void linux results in the following output

```
xyz@xyz-PC ~/Downloads % ./Sonixd-0.10.0.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'abstract-socket'
Require stack:
- /tmp/.mount_SonixdwFcJGy/resources/app.asar/node_modules/dbus-next/lib/connection.js
- /tmp/.mount_SonixdwFcJGy/resources/app.asar/node_modules/dbus-next/index.js
- /tmp/.mount_SonixdwFcJGy/resources/app.asar/node_modules/mpris-service/dist/index.js
- /tmp/.mount_SonixdwFcJGy/resources/app.asar/main.prod.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at createStream (/tmp/.mount_SonixdwFcJGy/resources/app.asar/node_modules/dbus-next/lib/connection.js:44:25)
    at createConnection (/tmp/.mount_SonixdwFcJGy/resources/app.asar/node_modules/dbus-next/lib/connection.js:81:33)
    at createClient (/tmp/.mount_SonixdwFcJGy/resources/app.asar/node_modules/dbus-next/index.js:10:20)
    at Object.module.exports.sessionBus (/tmp/.mount_SonixdwFcJGy/resources/app.asar/node_modules/dbus-next/index.js:41:10)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**To Reproduce**
1. Run the appimage

**Expected behavior**
The application starts.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Void Linux

**Additional context**

```
% echo $DBUS_SESSION_BUS_ADDRESS
unix:abstract=/tmp/dbus-zOHPZXW0Ki,guid=3c013553a64a357c6b7d980861a3fdca
```

It appears that the `abstract-socket` module is not installed inside the appimage.

**Comment by xyzz** [comment]
Since I've had the same issue with plexamp before, here's a workaround:

```
#!/bin/bash

set -ex

DBUS_PATH=$(echo $DBUS_SESSION_BUS_ADDRESS | awk -F '[=,]' '{ print $2 }')
rm -f /tmp/dbus-session-for-sonixd
socat UNIX-LISTEN:/tmp/dbus-session-for-sonixd,fork ABSTRACT-CONNECT:$DBUS_PATH &
SOCAT_PID=$!
trap 'kill -9 $SOCAT_PID' EXIT

sleep 0.5
DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-session-for-sonixd ./Sonixd-0.10.0.AppImage
```

**Comment by jeffvli** [comment]
Interesting.. I'm not quite sure how to go about fixing that on the production builds since the binaries are built using [electron-builder](https://www.electron.build/).

**Comment by xyzz** [comment]
could it be that since it's being built on macos host the dependency is not getting installed? It looks like abstract-socket is a native dep https://github.com/saghul/node-abstractsocket/blob/master/src/abstract_socket.cc

**Comment by l0l67** [comment]
Same problem on gentoo for me
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'abstract-socket'
Require stack:
- /tmp/.mount_SonixdNNDgba/resources/app.asar/node_modules/dbus-next/lib/connection.js
- /tmp/.mount_SonixdNNDgba/resources/app.asar/node_modules/dbus-next/index.js
- /tmp/.mount_SonixdNNDgba/resources/app.asar/node_modules/mpris-service/dist/index.js
- /tmp/.mount_SonixdNNDgba/resources/app.asar/main.prod.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at createStream (/tmp/.mount_SonixdNNDgba/resources/app.asar/node_modules/dbus-next/lib/connection.js:44:25)
    at createConnection (/tmp/.mount_SonixdNNDgba/resources/app.asar/node_modules/dbus-next/lib/connection.js:81:33)
    at createClient (/tmp/.mount_SonixdNNDgba/resources/app.asar/node_modules/dbus-next/index.js:10:20)
    at Object.module.exports.sessionBus (/tmp/.mount_SonixdNNDgba/resources/app.asar/node_modules/dbus-next/index.js:41:10)
```

**Comment by jeffvli** [comment]
I'll switch to one of github's ubuntu runners for the linux build for 0.12.0.

**Comment by jeffvli** [comment]
The 0.12.0 release is now out using one of githubs ubuntu runners.

Let me know if this error still persists.
